services:
  timescale:
    image: timescale/timescaledb:latest-pg17
    container_name: timescale
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: timescale
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8085:8080"
    depends_on:
      - timescale

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: keycloak
    command: start-dev --import-realm
    ports:
      - "8081:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./config/realm-export.json:/opt/keycloak/data/import/realm-export.json:ro
    networks:
      - rabbitmq_network

  rabbitmq:
    image: rabbitmq:4.1.0
    container_name: rabbitmq
    ports:
      - "5672:5672"    # AMQP default port
      - "15672:15672"  # Management UI
      - "1883:1883"    # MQTT port (must be exposed manually)
    environment:
      RABBITMQ_HOST: '%'
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./config/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./config/rabbitmq/certs/ca.crt:/etc/rabbitmq/certs/ca.crt:ro

    networks:
      - rabbitmq_network

  nginx-keycloak-proxy:
    image: nginx:alpine
    container_name: nginx-keycloak-proxy
    ports:
      - "8443:8443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - keycloak
    networks:
      - rabbitmq_network

volumes:
  timescale-data:
  keycloak-data:
  rabbitmq_data:

networks:
  rabbitmq_network:
    driver: bridge
