[versions]
spring-boot = "3.4.4"
spring-cloud = "2024.0.1"
kotlin = "1.9.25"
postgres = "42.7.5"

[libraries]
spring-boot-dependencies-bom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-dependencies-bom = { module = "org.springframework.cloud:spring-cloud-dependencies", version.ref = "spring-cloud" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgres" }

[plugins]
spring-dependencymanagement = "io.spring.dependency-management:1.1.7"
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
