# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      ARTIFACT_NAME: beecon-app
      RELEASE_VERSION: 0.0.0

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew bootJar

      - name: Find JAR file
        run: |
          JAR_FILE=$(ls -1 ${ARTIFACT_NAME}/build/libs/*.jar | head -n 1)
          if [ -z "$JAR_FILE" ]; then
            echo "No JAR file found!"
            exit 1
          fi
          echo "JAR_FILE=$JAR_FILE" >> $GITHUB_ENV
      
      - name: Move artifact
        run: |
          mkdir -p artifacts
          mv $JAR_FILE artifacts/${ARTIFACT_NAME}-${RELEASE_VERSION}.jar
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: beecon-app
          path: artifacts/${{ env.ARTIFACT_NAME }}-${{ env.RELEASE_VERSION }}.jar
          retention-days: 1
